export const storeProducts = [
{
    id: 1,
    title: 'Sandwich',
    img: "images/sandwich.jpg",
    price: 100,
    category: "1",
    time: '10-15 mins',
    info: "Sandwich Pakodas are tasty,crunchy deep-fried treats . These are made from paneer slices stuffed with Indian herbs and spices, dipped in gram flour batter and deep fried.They taste perfect with mint chutney .",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 2,
    title: 'Aloo Tikki',
    img: "images/alooTikki.jpg",
    price: 55,
    category: "1",
    time: '10-15 mins',
    info: "These are deep-fried, very thin, salted slices of potato that are usually served at room temperature. French fries have numerous variants, from thick-cut to shoestring, crinkle, curly and many other names. They are readily available at restaurants or Mac Donald outlet",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 3,
    title: 'Bread Pakoda',
    img: "images/breadPakoda.jpg",
    price: 120,
    category: "1",
    time: '5-10 mins',
    info: "Bread Pakodas are tasty,crunchy deep-fried treats . These are made from paneer slices stuffed with Indian herbs and spices, dipped in gram flour batter and deep fried.They taste perfect with mint chutney .",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 4,
    title: 'Chhole Bhature',
    img: "images/chholeBhature.jfif",
    price: 60,
    category: "1",
    time: '25-30 mins',
    info: "Bhatura is classic Indian deep fried puffed bread which is always associated with inseparable masala Chole. It is made from all purpose flour, yeast and vegetable oil. ",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 5,    
    title: 'Zucchini',
    img: "images/Zucchini.png",
    price: 100,
    category: "0",
    time: '30-40 mins',
    info: "Green, cylindrical squash are what most people think of when they think of zucchini, but the color can vary from a solid, deep green, to lighter shades with streaks or blotches of darker green. ",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 6,    
    title: 'Aloo Paratha',
    img: "images/alooParatha.jpg",
    price: 100,
    category: "1",
    time: '20-25 mins',
    info: "Aloo Paratha is a delicious shallow fried flaky bread, stuffed with mashed boiled potaoes, grated ginger, cilantro, cut chillies. These crispy prathas are generally fried with ghee.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 7,
    title: 'Dosa',
    img: "images/dosa.jpg",
    price: 200,
    category: "1",
    time: '20-25 mins',
    info: "Sambar, brimful of the goodness of toovar dal and assorted vegetables, it is nutritious everyday fare and is so versatile that it can be taken with dosa.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 8,
    title: 'Idli',
    img: "images/idli.jpg",
    price: 150,
    category: "1",
    time: '30-35 mins',
    info: "Idli is a south Indian savory cake popular throughout India. The cakes are made by steaming a batter consisting of fermented black lentils and rice. It is served with Sambhar and chutney.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 9,    
    title: 'Grilled Barbecue',
    img: "images/grilledBarbecue.png",
    price: 120,
    category: "0",
    time: '35-40 mins',
    info: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora autem maxime nesciunt ad dignissimos, animi totam eos quam quasi voluptas iure ratione optio? Repudiandae et autem labore cum libero nisi aut ea blanditiis voluptate. Quod, necessitatibus eligendi nemo ipsum.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 10,
    title: 'Noodles',
    img: "images/noodles.jpg",
    price: 80,
    category: "1",
    time: '15-20 mins',
    info: "Vegetable Noodles are madein chinese style by using boiled noodles, stir fried with vegetables like carrots, cabbage, beans with soy sauce.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 11,
    title: 'White Sauce Pasta',
    img: "images/pasta.jpg",
    price: 50,
    category: "1",
    time: '30-35 mins',
    info: "The creamy flavour of white sauce pasta may tingle your taste buds, pasta with canned diced tomatoes just after it's cooked.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 12,
    title: 'Patties',
    img: "images/patties.jpg",
    price: 70,
    category: "1",
    time: '10-20 mins',
    info: "Potato patties is a shallow fried cutlet with the boiled and mashed potatoes. The potato patties can be enjoyed as a filling for sandwiches, as a snack with chutney or as burger.",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 13,
    title: 'Pav Bhaji',
    img: "images/pavBhaji.jpg",
    price: 110,
    category: "1",
    time: '20-25 mins',
    info: "A spicy curry of mixed vegetables cooked in a special blend of spices and served with soft buttered",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 14,
    title: 'Rajma Chawal',
    img: "images/rajmachawal.jpg",
    price: 70,
    category: "1",
    time: '30-40 mins',
    info: "Delight for vegetarians, fresh cooked biryani with chunks of tandoori cottage cheese tikka",
    inCart: false,
    count: 0,
    total: 0
}, 
{
    id: 15,
    title: 'Red Sauce Pasta',
    img: "images/redSaucePasta.jpg",
    price: 80,
    category: "1",
    time: '20-25 mins',
    info: "Hungree Belly adaptation of the Italian classic, flavourful tomato sauce and cheesy",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 16,
    title: 'Samosa',
    img: "images/samosa.jpg",
    price: 20,
    category: "1",
    time: '10-15 mins',
    info: "Crispy pastry stuffed with spiced potatoes and peas.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 17,
    title: 'Pizza',
    img: "images/pizza.png",
    price: 90,
    category: "1",
    time: '25-30 mins',
    info: "No sauce, mozzarella, parmesan, garlic, oregano, and olive oil. Made with grande cheese and Caputo blue.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 18,
    title: 'Coffee',
    img: "images/coffee.jpg",
    price: 70,
    category: "1",
    time: '30-40 mins',
    info: "The coffee has a crisp, bright flavor, with subtle hints of citrus and rich chocolates.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 19,
    title: 'Tea',
    img: "images/tea.jpg",
    price: 40,
    category: "1",
    time: '5-10 mins',
    info: "Tea is bright in colour and greater in flavor and freshness, and thus is the most sought after.",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 20,
    title: 'French Fries',
    img: "images/frenchFries.png",
    price: 90,
    category: "1",
    time: '10-20 mins',
    info: "These are deep-fried, very thin, salted slices of potato that are usually served at room temperature. French fries have numerous variants, from thick-cut to shoestring, crinkle, curly and many other names. They are readily available at restaurants or Mac Donald outlets",
    inCart: false,
    count: 0,
    total: 0
},
{
    id: 21,
    title: 'Chocolate Cake',
    img: "images/chocolateCake.png",
    price: 90,
    category: "1",
    time: '25-30 mins',
    info: "Alternating layers of chocolate cake and chocolate mousse are topped with dark chocolate ganache and finished with a generous sprinkling of chocolate shavings.",
    inCart: false,
    count: 0,
    total: 0
}
];

export const detailProduct = {
    id: 1,
    title: 'Sandwich',
    img: "images/sandwich.jpg",
    price: 100,
    category: "1",
    time: '10-15 mins',
    info: "Sandwich Pakodas are tasty,crunchy deep-fried treats . These are made from paneer slices stuffed with Indian herbs and spices, dipped in gram flour batter and deep fried.They taste perfect with mint chutney .",
    inCart: false,
    count: 0,
    total: 0
};

